### ISSUE TITLE
Alarm not arming or disarming correctly

### ISSUE THREAD

**Issue by kramer9802** [statusbits/smartalarm#23] opened 2015-01-22 18:03 UTC
Two times when the system performed a "Good Morning" and switch to Home the system doesn't disarm. The latest occurrence was yesterday morning. It worked when I manually went from home to night to home. Then last night when the system performed a "Good Night", but the alarmed didn't arm. This isn't a consistent problem because for the most part it has worked for the last few weeks. I did wonder if the recent Smart Hub update has something to with it. Please Advise.

Thanks,

Kevin

**Comment by mbmccormick** [comment] 2015-01-22 18:54
I can confirm that I am also having this issue, but again, it does not seem consistent. When I uninstalled and re-installed (I just got my SmartThings this week, so my setup wasn't too detailed yet) it seems to have fixed the issue. Haven't been able to pinpoint why, though.

**Comment by jpetrone84** [comment] 2015-01-22 21:50
There were some system issues last night, controlling devices. IDK if that plays any role.

**Comment by hreed1985** [comment] 2015-01-22 21:52
I am also having the same issue.

**Comment by statusbits** [comment] 2015-01-23 06:27
> This isn't a consistent problem because for the most part it has worked for the last few weeks. 

It's probably due to ST system issues. SmartThings is an event-driven system. Once in a while event queues become clogged, which causes either delays (best case) or in the worst case some events being dropped.

**Comment by hreed1985** [comment] 2015-01-23 17:21
I still have the issue after I have disarmed the alarm this morning. I believe this started right after my second hub update this week.

**Comment by kramer9802** [comment] 2015-01-23 17:28
I manually set the Alarm last night and it was able to disarm this morning. Perhaps there is a log jam of events on the hub, but it has been executing the "Good Morning/Night" and switching to the "Night"/"Home", it is like the event is not always picked up by the app. I am new to this IDE, so I was trying to find where the logs in the application actually drop so that I could see if the App actually caught the event.  If there is a log jam it is probably from the outlet smart things constantly poling to telling how many watt is being used ;), which is annoying btw. Probably something I need to report to Smart Things as well.

**Comment by statusbits** [comment] 2015-01-24 17:48
All events go through the cloud. This is why any problem with event queues affects many people simultaneously.

**Comment by statusbits** [comment] 2015-01-25 07:44
Duplicate of #20.

**Closed by statusbits** 2015-01-25 07:44 UTC
Labels: duplicate

**Comment by kramer9802** [comment] 2015-01-26 00:36
Is there a way to disarm this application without an event? That would be an nice enhancement. To add a manual arm/disarm button in the application. The other night the Good Night event fired and armed but a few minutes later I had to let my dog out and did a good morning to disarm, which went fine. Then after that I spent twenty minutes trying to get it to arm. The application would fail to save over and over again. I restarted my application on my phone and restarted the hub. I finally got it to work, but a disarm/rearm  button would have made this simpler.

**Comment by statusbits** [comment] 2015-01-26 04:11
> Is there a way to disarm this application without an event?

There used to be, but it only worked on iPhone, because ST Android app is behind in terms of UI features, etc. So it was removed to be consistent. I may revisit this in the next release.
Currently, you can use a remote control (e.g. Aeon Minimote) or REST API in addition to mode changes to control SmartAlarm.
