### ISSUE TITLE
Alarm re-arming by itself after trigger even though it was disarmed

### ISSUE THREAD

**Issue by jpetrone84** [statusbits/smartalarm#20] opened 2015-01-19 11:15 UTC
If the alarm disarms by mode change (the motion sensor by my front door is set to mode change to home when things start happening, and as a result disarm smart alarm) the mode change came through for this but it looks like the alarm activated because the front door (entrance way) was opened at the same time the motion was registering for the mode change. The event came through to disarm, which is good. But 3 minutes later the alarm rearmed itself to stay even though the mode was set to home and not stay or away. I'm assuming this happened because of the alarm activation for that brief second and the disarm/mode change  didn't clear the re-arm duration/window.

**Comment by rayzurbock** [comment] 2015-01-21 01:22
I am also seeing this behavior.
1. Alarm is armed
2. Alarm is triggered
3. Mode changes during alarm event, Alarm deactivates.
4. 3 minutes later, alarm rearms even though it should not in the new mode.
5. Alarm triggers again, repeat...
* I can go into the Smart App and hit Done after the mode change to an unarmed mode during an alarm event and stop the loop of rearming and triggering.

**Comment by jpetrone84** [comment] 2015-01-21 01:32
I was able to break the loop by changing the mode to one that would arm the alarm and then changing to a mode that would disarm.

**Comment by statusbits** [comment] 2015-01-23 06:18
This definitely is not supposed to happen. I'd like to see some logs if anyone can collect them.

Re-arming of Smart Alarm is done by a scheduled task which is scheduled to execute 3 minutes after the alarm. If Smart Alarm is disarmed (either by mode change or other means), the first thing it does is cancel all scheduled tasks. If Smart Alarm is re-armed even though it was disarmed after the alarm, that would indicate that the re-arming task is not cancelled for whatever reason.

**Comment by statusbits** [comment] 2015-01-23 06:52
I ran a quick test and Smart Alarm worked as expected.

1. Initial state - disarmed.

2. Arm Smart Alarm by setting mode to 'Away'.

Smart Alarm receives 'location' event and arms in 'Away' mode:
 10:32:04 PM PST: debug onLocation(Away)
 10:32:04 PM PST: debug armAway()
 10:32:04 PM PST: debug resetPanel()
 10:32:04 PM PST: trace Deleting all scheduled jobs for InstalledSmartApp: xxxx

Next, Smart Alarm schedules delayed action to arm 'Entrance' zones:
 10:32:05 PM PST: debug myRunIn(30)
 10:32:05 PM PST: trace Deleting scheduled job 'armEntranceZones' for InstalledSmartApp: xxxx
 10:32:05 PM PST: trace Scheduling 'armEntranceZones' for InstalledSmartApp: xxxx
 10:32:05 PM PST: debug 'armEntranceZones' scheduled to run at Fri Jan 23 06:32:35 UTC 2015
 10:32:05 PM PST: trace Home alarm is Armed Away.

Entrance zones are armed few seconds later:
 10:32:16 PM PST: debug armEntranceZones()
 10:32:16 PM PST: trace Entrance zones are armed
 10:32:16 PM PST: debug notify(Entrance zones are armed)

3. I trip the door sensor.

Smart Alarm receives 'contact open' event and sets off an alarm:
 10:32:53 PM PST: debug onZoneEvent(Office Door, contact)
 10:32:53 PM PST: debug activateAlarm()
 10:32:54 PM PST: trace Alarm at Home!
Office Door
 10:32:54 PM PST: debug notify(Alarm at Home!
Office Door)
 10:32:54 PM PST: debug notifyVoice()

Smart Alarm schedules reset function to run 3 minutes later:
 10:32:54 PM PST: debug myRunIn(180)
 10:32:54 PM PST: trace Deleting scheduled job 'resetPanel' for InstalledSmartApp: xxxx
 10:32:54 PM PST: trace Scheduling 'resetPanel' for InstalledSmartApp: xxxx
 10:32:54 PM PST: debug 'resetPanel' scheduled to run at Fri Jan 23 06:35:54 UTC 2015

4. I disarm Smart Alarm by changing mode to 'Home' before it's re-armed.

Smart Alarm receives 'location' event and disarms:
 10:33:15 PM PST: debug onLocation(Home)
 10:33:15 PM PST: debug disarm()
 10:33:15 PM PST: debug resetPanel()
 10:33:15 PM PST: trace Deleting all scheduled jobs for InstalledSmartApp: 
 10:33:21 PM PST: trace Home alarm is Disarmed.
 10:33:21 PM PST: debug notify(Home alarm is Disarmed.)
 10:33:22 PM PST: debug notifyVoice()

Since the scheduled 'resetPanel' is cancelled, it does not re-arm after 3 minutes.

**Comment by jpetrone84** [comment] 2015-01-23 15:00
Is it possible that it was disarming so fast that the reset function was coming after the disarm? In my case the alarm would trip and then the stupid motion sensor at that door would immediately change the mode, disarming the alarm. I'll have to mess with it this weekend or after work tonight. I no longer have that motion sensor changing modes, because I quickly realized it wasn't practical.

**Comment by statusbits** [comment] 2015-01-25 07:42
SmartThings does not makes any guarantees about order of events. I have seen many times while developing apps that events can arrive out of order, sometimes with several seconds delays. This makes writing time-critical apps extremely difficult.

**Comment by statusbits** [comment] 2015-01-25 08:54
Based on multiple bug reports and a couple of logs provided by users, I conclude that the issue was caused by SmartThings failure to cancel scheduled tasks, which resulted in failure of Smart Alarm disarming logic.

**Comment by CosmicPuppy** [comment] 2015-01-25 21:32
Just curious: Is this problem now tied to a specific SmartThings "bug/issue tracking number" and/or at least a Support Ticket (ZenDesk) Number? Multiple SmartApps must be susceptible to this "SmartThings failure...", so somehow back-linking them to referenceable details might be helpful. Perhaps?

**Comment by statusbits** [comment] 2015-01-25 22:11
I did not formally open a support ticket because I was not able to reproduce the issue personally and therefore I don't have "hard evidence" to back it up.

**Comment by CosmicPuppy** [comment] 2015-01-26 00:38
Understood. Thanks! *Hopefully they still have a "feel" from the various threads related to scheduling and are putting the pieces of the puzzle together.*

**Comment by statusbits** [comment] 2015-02-15 21:37
I've traced this issue back to `TimeoutException` (i.e. the app exceeding 20 seconds execution limit) during execution of the `unschedule()` API. See details in this SmartThings Community discussion:

http://community.smartthings.com/t/unschedule-api-execution-time-too-long/11232

**Comment by yannoehl** [comment] 2015-04-08 15:14
I can confirm that the issue above is still occurring. In the last week two more 2 false alarms.

**Comment by jpetrone84** [comment] 2015-04-08 20:01
Look in the thread on the ST community, someone put a line of code to add to the app to help with this. 

-Jordan

**Comment by yannoehl** [comment] 2015-04-08 20:20
Jordan... Not able to find said code. Would love a link if you have it.
Thanks!

**Comment by jpetrone84** [comment] 2015-04-09 01:56
@yannoehl , check this out. http://community.smartthings.com/t/smart-alarm-is-here/3316/329?u=chrisb

- Jordan

**Comment by yannoehl** [comment] 2015-04-09 02:31
Thanks Jordan! I'll give that code a try.

**Comment by statusbits** [comment] 2015-06-06 19:41
This issue does not seem to be occurring with version 2.4. Closing for now. Please re-open if you see it again.

**Closed by statusbits** 2015-06-06 19:41 UTC
